name: Feature Request
description: Suggest a new feature for avSign.lite
title: "[FEATURE]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help shape the future of avSign.lite.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Resource Management
        - Layout Editor
        - Templates
        - Playlists/Programs
        - Device Management
        - User Interface
        - Performance
        - Security
        - Platform Support
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: "I'm always frustrated when I have to manually resize each zone in my layout..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Be specific about the user experience.
      placeholder: |
        I'd like a "Smart Layout" feature that automatically sizes zones based on content aspect ratio.

        For example:
        1. User uploads a 16:9 video
        2. System suggests a layout that optimizes for 16:9 content
        3. User clicks "Apply" and zones are automatically sized
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've tried manually calculating zone sizes in a spreadsheet, but it's time-consuming..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Importance
      description: How important is this feature to you?
      options:
        - Nice to have (would be cool, but not essential)
        - Would be helpful (would save time or improve workflow)
        - Important (significant impact on usability)
        - Critical (blocks important use case)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        I manage digital signage for 10 retail stores. We frequently update content with varying aspect ratios.
        This feature would save us 30 minutes per store when creating new layouts.

  - type: dropdown
    id: willing-to-test
    attributes:
      label: Beta Testing
      description: Would you be willing to test this feature if we implement it?
      options:
        - "Yes, I'd love to test it"
        - "Maybe, depending on timing"
        - "No, but I'd use it when it's released"
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have mockups, screenshots from other tools, or visual examples, attach them here
      placeholder: "Drag and drop images here..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would help us understand this feature request
      placeholder: "Similar features exist in [other tool], but avSign.lite could do it better by..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing feature requests to avoid duplicates
          required: true
        - label: This feature aligns with avSign.lite's core mission (offline-first digital signage)
          required: false
